version: "3.9"  # optional since v1.27.0
services:
# mongodb service
  mongoDb:
    container_name: db_container
    image: mongo:latest
    platform: linux/amd64
    restart: always
    ports:
      - 2717:27017  # port 2717 of local machine now connects to port 27017 of docker container
    volumes:
      - mongoDb:/data/db

# nodejs api
  api:
    build: .
    ports: 
      -  3000:3500  # 3000 on local to 3500 in docker
    # volumes:  # only for dev
    #   - .:/app # only for dev
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongoDb:27017
      MONGODB_URI: mongodb://mongoDb:27017
      DB_NAME: torposdb
      DB_USER: ""
      DB_PASS: ""
    depends_on:
      - mongoDb
     
volumes:
  mongoDb: {}
#  docker compose build  # rebuild app 
#  docker compose up|down -d
