GET http://localhost:3000/api/login
Authorization:   Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1ODIxODUwMzd9.RmNj9uJ9xoYs2VUNKQHwec75RrdGFtM0Ut_j-sNZYkM


###
POST http://localhost:3000/api/login

Content-Type: application/json

{
    "username": "k1"
}